---
repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        name: "Black (python code formatting)"
        entry: bash -c 'black "$@";' --
        language: python
        types: [ python ]

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
        name: "isort (python library formatter)"
        entry: bash -c 'isort "$@";' --
        language: python
        types: [ python ]

  - repo: local
    hooks:
      - id: json-format-python
        name: "JSON format (Python)"
        entry: python -c 'import sys, json; file = sys.argv[1]; data = json.load(open(file)); open(file, "w").write(json.dumps(data, indent=2) + "\n")'
        language: python
        files: '.*\.json$'
        types: [file]